spring:
  h2.console.enabled: true
  datasource:
    #Exemplo banco local
    #url: jdbc:h2:~/petshop.db
    url: jdbc:h2:mem:petshop
  jpa:
    # create-drop - criar tudo do zero
    # update - atualiza as diferenças
    # none - nada
    # validate - não altera estrutura, mas falha
    hibernate.ddl-auto: update
    hibernate.format_sql: false
